---
title: "Covid-Chile"
author: "`r invisible((Sys.setlocale('LC_TIME', 'Spanish'))); format(Sys.Date(), '%d %B %Y')`"
output: 
  flexdashboard::flex_dashboard:
    self_contained: false
    lib_dir: www
    orientation: rows
    css: css/style.css
    favicon: www/favicon.png    
    social: ["twitter", "facebook", "linkedin"]
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(highcharter)
library(RcppRoll)
library(reactable)
library(htmltools)

source("R/00-parametros.R", encoding = "UTF-8")
source("R/01-productos.R", encoding = "UTF-8")
source("R/02-graficos-tablas.R", encoding = "UTF-8")
source("R/03-funciones-auxiliares.R", encoding = "UTF-8")
source("R/04-value-boxes.R", encoding = "UTF-8")
```

Inicio {data-icon="fa-tachometer-alt"}
=====================================  

Row {data-height=230}
-----------------------------------------------------------------------

### 

```{r}
value <- vb_confirmados() %>% filter(tipo == "casos_totales") %>% pull(descripcion)
caption <- "Confirmados"
info <- vb_confirmados() %>% filter(tipo != "casos_totales") %>% pull(descripcion)

valueBoxCaptions(value, caption, info)

```

### 

```{r}
valueBox("31.234", caption = "Fallecidos", icon = NULL, color = NULL, href = NULL)
```

### 

```{r}
valueBox("65%", caption = "Vacunación", icon = NULL, color = NULL, href = NULL)
```

### 

```{r}
valueBox("3.230", caption = "UCI", icon = NULL, color = NULL, href = NULL)
```


Row 
-----------------------------------------------------------------------

###

```{r}
grafico_confirmados_diarios()
```

###

```{r}
grafico_defunciones_diarias()
```

###

```{r}
grafico_porcentaje_vacunacion()
```

Row 
----------------------------------------------------------------------- 

### 

```{r}
grafico_activos_media_movil_7_dias()
```

### 

```{r}
grafico_pacientes_uci()
```

###

```{r}
```

Region {data-icon="fa-map-marked-alt" data-orientation=columns}
=====================================  

Column {data-width=900}
-----------------------------------------------------------------------

### 

<script src="geojson/regiones_geojson.js"></script>

```{r una_de_dos}
# tabla_region()
tabla_region2()
```

Column
-----------------------------------------------------------------------

### 

```{r}
grafico_region()
```
 
### 

```{r}
grafico_defunciones_por_region_100k_hab()
```

<script>
PARS = `r jsonlite::toJSON(PARS)`
</script>

```{js reactable}
function myFunction(id) {

  var hc_mapar = $('#hc_mapa_region').highcharts();
  var hc_falle = $('#hc_fallecimientos_region').highcharts();
  //var hc_act7m = $('#hc_activos_media_movil_7_dias_region').highcharts();

  //hc_mapar.get('region').update({ mapData: Highcharts.maps[id] });
  // while (hc_mapar.series.length) { hc_mapar.series[0].remove(); }
  
  if(id != hc_mapar.get('region').options.region) {
    hc_mapar.get('region').remove();
    hc_mapar.addSeries({id: 'region', mapData: Highcharts.maps[id], region: id});
  }

  for (var i = 0; i <= (16 - 1); i++) {
    hc_falle.series[i].update({color: PARS.colors.gray[0], lineWidth: 1, zIndex: 0});
    //hc_act7m.series[i].update({color: PARS.colors.gray[0], lineWidth: 1, zIndex: 0});
  }
  
  hc_falle.get(id).update({color: PARS.colors.primary[0], lineWidth: 4, zIndex: 1});
  //hc_act7m.get(id).update({color: PARS.colors.primary[0], lineWidth: 4, zIndex: 1});

}
```

```{js DT, eval=FALSE}  
document.addEventListener('DOMContentLoaded', function() {

  var table = $('#DataTables_Table_0').DataTable()
  
  $('#tabla_region tbody').on('mouseover', 'tr', function () {
  
    var d = table.row( this ).data();
    var idn = d[1]
    myFunction(idn);
    
  });
    
}, false);
```

Vacunación {data-icon="fa-syringe"}
=====================================  

Row 
-----------------------------------------------------------------------

### 

```{r}
grafico_porcentaje_vacunacion_edad()
```

### 

```{r}
```

Row 
-----------------------------------------------------------------------

### 

```{r}
grafico_porcentaje_vacunacion_edad_fecha()
```

Mortalidad {data-icon="fa-ribbon"}
=====================================  

Row 
-----------------------------------------------------------------------

### 

```{r}
grafico_defunciones_diarias()
```

### 

```{r}
grafico_letalidad()
```

Row 
-----------------------------------------------------------------------

### 

```{r}
grafico_defunciones_esperadas_arima()
```

### 

```{r}
grafico_defunciones_semanales_pandemia()
```

Acerca {data-icon="fa-question-circle"}
=====================================  

Row {data-height=500}
-----------------------------------------------------------------------

### 

```{r}
```