on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 0 * * 0"

name: update

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.1'

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render index.Rmd
        run: |
          rmarkdown::render("index.Rmd")
        shell: Rscript {0}          
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "updating data and report" --author 'Joshua Kunst <jbkunst@gmail.com>'
          git push
